export default {
        data: [
          {
            location_id: '10716910',
            name: "Chef Mamma's",
            latitude: '10.80826',
            longitude: '106.66454',
            num_reviews: '24',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.169757843017578',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1393',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,168 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.2539089280176141',
            distance_string: '0.3 km',
            bearing: 'northwest',
            rating: '4.0',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d10716910-Reviews-Chef_Mamma_s-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d10716910-Chef_Mamma_s-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 3848 6478',
            website: 'https://www.facebook.com/ChefMammas/?fref=nf',
            email: 'support@chefmamma.vn',
            address_obj: [Object],
            address: 'A43 Truong Son Tan Binh Dist, Ho Chi Minh City Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [Array],
            establishment_types: [Array]
          },
          {
            location_id: '8299650',
            name: 'iSushi Truờng Son',
            latitude: '10.807797',
            longitude: '106.66405',
            num_reviews: '24',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.1156749725341797',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1761',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,472 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.2762021666884339',
            distance_string: '0.3 km',
            bearing: 'west',
            rating: '3.5',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d8299650-Reviews-ISushi_Tru_ng_Son-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d8299650-ISushi_Tru_ng_Son-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 3848 5512',
            website: 'http://isushi.com.vn',
            address_obj: [Object],
            address: 'A43 Truong Son, Quan Tan Binh, Ho Chi Minh City 70000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '8327527',
            name: "Al Fresco's",
            latitude: '10.808975',
            longitude: '106.66476',
            num_reviews: '62',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [Array],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.335206985473633',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '797',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#682 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.29365975329632477',
            distance_string: '0.3 km',
            bearing: 'northwest',
            rating: '4.0',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d8327527-Reviews-Al_Fresco_s-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d8327527-Al_Fresco_s-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 3547 4363',
            website: 'http://alfrescos.com.vn',
            address_obj: [Object],
            address: '30 Truong Son Tan Binh, Ho Chi Minh City 70000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            booking: [Object],
            reserve_info: [Object],
            establishment_types: [Array]
          },
          {
            location_id: '15050914',
            name: 'Golden Elephant Thai Restaurant',
            latitude: '10.80495',
            longitude: '106.66428',
            num_reviews: '8',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.227477550506592',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1116',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#935 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.31591263208319104',
            distance_string: '0.3 km',
            bearing: 'southwest',
            rating: '5.0',
            is_closed: false,
            open_now_text: 'Closed Now',
            is_long_closed: false,
            price_level: '$$ - $$$',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d15050914-Reviews-Golden_Elephant_Thai_Restaurant-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d15050914-Golden_Elephant_Thai_Restaurant-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 3811 1519',
            website: 'http://www.nhahangconvoivang.com',
            email: 'convoivang34@yahoo.com',
            address_obj: [Object],
            address: '105 Tran Quoc Hoan Truong Son, Ward 4, Tan Binh, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '293925',
            ad_position: 'inline2',
            ad_size: '8X8',
            doubleclick_zone: '',
            detail: '0',
            page_type: 'restaurants',
            mob_ptype: 'app_restaurants'
          },
          {
            location_id: '7040251',
            name: 'Thai House Restaurant',
            latitude: '10.807826',
            longitude: '106.6635',
            num_reviews: '13',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.1126811504364014',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1789',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,495 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.3337715136544646',
            distance_string: '0.3 km',
            bearing: 'west',
            rating: '4.0',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d7040251-Reviews-Thai_House_Restaurant-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d7040251-Thai_House_Restaurant-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84-83-38115542',
            website: 'https://www.facebook.com/pages/Thai-House-Viet-Nam/291929560820780?sk=timeline',
            address_obj: [Object],
            address: '21B Hau Giang, Ward 4, Tan Binh District, Ho Chi Minh City 70000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '17526685',
            name: 'HoaVien',
            latitude: '10.80368',
            longitude: '106.66622',
            num_reviews: '1',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.0',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3604',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,986 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.3572493684472173',
            distance_string: '0.4 km',
            bearing: 'south',
            rating: '3.0',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d17526685-Reviews-HoaVien-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d17526685-HoaVien-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 3997 7666',
            website: 'http://www.hoavien.vn',
            email: 'hoavienbia@vnn.vn',
            address_obj: [Object],
            address: '16 Pho Quang St, Ho Chi Minh City Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '14916434',
            name: 'Big Pig BBQ & Beer',
            latitude: '10.809969',
            longitude: '106.66504',
            num_reviews: '29',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.1814751625061035',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1321',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,104 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.37388673524212057',
            distance_string: '0.4 km',
            bearing: 'northwest',
            rating: '3.5',
            is_closed: false,
            open_now_text: 'Closes in 11 min',
            is_long_closed: false,
            price_level: '$',
            price: '$5 - $20',
            description: 'Offering the best in American style Ribs & Pizzas, along with Vietnamese favorites like hot-pot and grilled seafood, Big Pig BBQ & Beer also has the largest selection of craft beers in Tan Binh District. Open early for breakfast, with fantastic lunch specials, hearty meals and late night snacks, the team at Big Pig BBQ & Beer is ready to welcome you.',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d14916434-Reviews-Big_Pig_BBQ_Beer-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d14916434-Big_Pig_BBQ_Beer-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 3547 4034',
            website: 'http://www.utit.vn',
            email: 'bigpig@utit.vn',
            address_obj: [Object],
            address: '46 Truong Son Ward 2, Tan Binh, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            booking: [Object],
            reserve_info: [Object],
            establishment_types: [Array]
          },
          {
            location_id: '10500781',
            name: 'ICHIBAN Japanese Hotpot Buffet',
            latitude: '10.803675',
            longitude: '106.66495',
            num_reviews: '8',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '2.7103042602539062',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3878',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#3,223 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.3909309440613533',
            distance_string: '0.4 km',
            bearing: 'southwest',
            rating: '5.0',
            is_closed: false,
            open_now_text: 'Closed Now',
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$6 - $19',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d10500781-Reviews-ICHIBAN_Japanese_Hotpot_Buffet-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d10500781-ICHIBAN_Japanese_Hotpot_Buffet-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 3842 1991',
            website: 'http://www.ichibanhotpot.com',
            email: 'info@ichibanhotpot.com',
            address_obj: [Object],
            address: '14A Phan Dinh Giot Street, Ward 2, Tan BInh District, Ho Chi Minh, Vietnam, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '6901416',
            name: 'LAU DAI VANG',
            latitude: '10.80341',
            longitude: '106.66555',
            num_reviews: '8',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.0085771083831787',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3516',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,912 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.39780065121675123',
            distance_string: '0.4 km',
            bearing: 'south',
            rating: '4.0',
            is_closed: false,
            open_now_text: 'Closes in 11 min',
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$20',
            description: "The Best Steakhouse in town. We serve quality USDA Beef From America. Besides, we carry a huge wine's collection of the world. We committed to provide professional service and romantic atmosphere to you.",
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d6901416-Reviews-LAU_DAI_VANG-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d6901416-LAU_DAI_VANG-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 5449 2403',
            website: 'http://www.laudaivang.vn',
            email: 'laudaivang2010@yahoo.com',
            address_obj: [Object],
            address: '10 / 7 Phan Dinh Giot Street , Ward 2, Tan Binh District, Ho Chi Minh City 0084 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '16828251',
            name: 'Spice India Restaurant',
            latitude: '10.807945',
            longitude: '106.66291',
            num_reviews: '7',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.129150152206421',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1664',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,396 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.398986163601225',
            distance_string: '0.4 km',
            bearing: 'west',
            rating: '4.5',
            is_closed: false,
            open_now_text: 'Closed Now',
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$5 - $20',
            description: 'Indian cuisine. Booking, deliver. Take away food. Free parking. Television, service beer. Wifi. Accept visa master card',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d16828251-Reviews-Spice_India_Restaurant-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d16828251-Spice_India_Restaurant-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 93 232 38 79',
            website: 'https://www.facebook.com/spiceindiatanbinh',
            email: 'spiceindia.tanbinh@gmail.com',
            address_obj: [Object],
            address: '42 Hau Giang Ward 4, Tan Binh, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '12530630',
            name: 'Hansol Korea Restaurant',
            latitude: '10.807737',
            longitude: '106.6617',
            num_reviews: '3',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.0873610973358154',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2031',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,685 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.5224465279100114',
            distance_string: '0.5 km',
            bearing: 'west',
            rating: '4.5',
            is_closed: false,
            is_long_closed: false,
            price_level: '$',
            price: '$120,000 - $150,000',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d12530630-Reviews-Hansol_Korea_Restaurant-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d12530630-Hansol_Korea_Restaurant-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 90 802 49 20',
            website: 'https://www.facebook.com/hansol11/',
            address_obj: [Object],
            address: '114A Thang Long Ward 4, Tan Binh District, Ho Chi Minh City Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '17885870',
            name: 'Seafood Restaurant Bien Dong',
            latitude: '10.80174',
            longitude: '106.66575',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '0.577098494658657',
            distance_string: '0.6 km',
            bearing: 'south',
            is_closed: false,
            open_now_text: 'Open Now',
            is_long_closed: false,
            price_level: '$',
            price: '$100,000 - $300,000',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d17885870-Reviews-Seafood_Restaurant_Bien_Dong-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d17885870-Seafood_Restaurant_Bien_Dong-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 3844 2534',
            website: 'http://nhahangbiendong.com',
            email: 'nhahangbiendong.saigon@gmail.com',
            address_obj: [Object],
            address: '1A - 1B Pho Quang Ward 2, Tan Binh District, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '293925',
            ad_position: 'inline3',
            ad_size: '8X8',
            doubleclick_zone: '',
            detail: '0',
            page_type: 'restaurants',
            mob_ptype: 'app_restaurants'
          },
          {
            location_id: '7070089',
            name: 'Vuvuzela',
            latitude: '10.81244',
            longitude: '106.66704',
            num_reviews: '21',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.1157004833221436',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1760',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,471 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.6221123991655926',
            distance_string: '0.6 km',
            bearing: 'north',
            rating: '3.5',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            description: 'Vuvuzela - Beer Club is a restaurant which serves draught beer in the style of bar. This is an enchanted redezvous for customers who desire draught beer and feel excited about new stuff. At Vuvuzela - Beer Club, almost any draught beer can be found from popular ones like: Tiger, Calsbergs to Zamky - one type of Czech draught beer known for the first time in Vietnam.',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d7070089-Reviews-Vuvuzela-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d7070089-Vuvuzela-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+(84)38486180',
            website: 'http://vuvuzela.com.vn/',
            email: 'hcm.suppor@ggg.com.vn',
            address_obj: [Object],
            address: '4a3, Truong Son, Dist Tan Binh, Ho Chi Minh City 70000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '13358770',
            name: 'Vua Hai San Hon Dao',
            latitude: '10.813',
            longitude: '106.66731',
            num_reviews: '2',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.0341293811798096',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2970',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,438 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.6877797722313066',
            distance_string: '0.7 km',
            bearing: 'north',
            rating: '4.0',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d13358770-Reviews-Vua_Hai_San_Hon_Dao-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d13358770-Vua_Hai_San_Hon_Dao-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            address_obj: [Object],
            address: '48 Lam Son Ward 2, Tan Binh Dist, Ho Chi Minh City Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '19175121',
            name: 'Bun Bo Hue O Cuc',
            latitude: '10.80359',
            longitude: '106.66078',
            num_reviews: '1',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.0430033206939697',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2704',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,234 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.7151141051334973',
            distance_string: '0.7 km',
            bearing: 'southwest',
            rating: '5.0',
            is_closed: false,
            open_now_text: 'Closes in 11 min',
            is_long_closed: false,
            price_level: '$',
            price: '$2 - $4',
            description: 'The restaurant specializes in Hue dishes, so here serves many delicious dishes of the ancient capital such as duck cake, shrimp cakes with wet meat, delicious cakes ... However, Ngu Binh beef noodle soup is still considered to be outstanding and selected by many people. enjoy because you think this place is so old Hue ... conservative!',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d19175121-Reviews-Bun_Bo_Hue_O_Cuc-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d19175121-Bun_Bo_Hue_O_Cuc-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 90 647 47 07',
            website: 'https://bunbohueocuc.business.site/',
            email: 'nhong299@gmail.com',
            address_obj: [Object],
            address: '69 Thang Long Ward 4, Tan Binh, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '11618502',
            name: 'Dau Homemade',
            latitude: '10.81335',
            longitude: '106.66606',
            num_reviews: '54',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.2412307262420654',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1057',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#891 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.7203470892500963',
            distance_string: '0.7 km',
            bearing: 'north',
            rating: '3.5',
            is_closed: false,
            open_now_text: 'Closed Now',
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$1 - $6',
            description: `Dau Homemade includes a chain of diners that specialize in "bún đậu mắm tôm" (fermented shrimp paste with deep fried tofu and rice vermicelli) and other Hanoi's specialty. The word "homemade" not only means the freshness of the dishes, but also aims to bring customer the feeling of authenticity as they are enjoying the meals in the atmosphere and culture of Hanoi - the north of Vietnam, right in Ho Chi Minh City. Dau Homemade wishes to guide customer from daily normal dishes in every northern Vietnamese family to fascinating and surprising light meals and street food in Hanoi, in the most original and authentic ways. Together with the dishes, the space and decoration here also makes customers feel like travelling among the narrow and ancient street of Hanoi. Moreover, if you are lucky enough, you will find surprise as you are enjoying acoustic music or special shows while you are treating yourself here! Come to Dau Homemade, and taste the authentic culture right at your dish!`,
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d11618502-Reviews-Dau_Homemade-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d11618502-Dau_Homemade-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 93 808 82 84',
            website: 'https://www.facebook.com/BunDauMamTomDauHomemade/',
            email: 'dauhomemade@gmail.com',
            address_obj: [Object],
            address: 'So 6 Hong Ha Ward Ben Thanh , District 1, Ho Chi Minh City 700 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '17760960',
            name: 'Cha Ca Ha Noi Xua',
            latitude: '10.81324',
            longitude: '106.6679',
            num_reviews: '2',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.077648162841797',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2138',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,779 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.7260417832447029',
            distance_string: '0.7 km',
            bearing: 'north',
            rating: '5.0',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$$$',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d17760960-Reviews-Cha_Ca_Ha_Noi_Xua-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d17760960-Cha_Ca_Ha_Noi_Xua-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 98 250 83 72',
            website: 'https://www.facebook.com/chacahanoixua/',
            address_obj: [Object],
            address: '42 Hong Ha Ward 2, Tan Binh, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '16859142',
            name: 'Family Food Paradise - CT Plaza',
            latitude: '10.813358',
            longitude: '106.665565',
            num_reviews: '4',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.0603420734405518',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2387',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,975 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.7260808097575966',
            distance_string: '0.7 km',
            bearing: 'north',
            rating: '4.0',
            is_closed: false,
            is_long_closed: false,
            price_level: '$',
            price: '$20,000 - $80,000',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d16859142-Reviews-Family_Food_Paradise_CT_Plaza-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d16859142-Family_Food_Paradise_CT_Plaza-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 6297 1781',
            website: 'http://familyfoodvietnam.com',
            email: 'ct@familyfoodvietnam.com',
            address_obj: [Object],
            address: '5th Floor, 60A Truong Son Tan Binh, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '7896450',
            name: 'Exit Sports Bar Hcm',
            latitude: '10.80041',
            longitude: '106.66551',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '2.24613881111145',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '4025',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#3,345 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.7271507567399093',
            distance_string: '0.7 km',
            bearing: 'south',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d7896450-Reviews-Exit_Sports_Bar_Hcm-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d7896450-Exit_Sports_Bar_Hcm-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 90 292 85 05',
            address_obj: [Object],
            address: '1a12 Truong Son, Tan Binh District Near Hoang Van Thu Park, Ho Chi Minh City 70000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '10205168',
            name: 'The Catchy',
            latitude: '10.800388',
            longitude: '106.665344',
            num_reviews: '2',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.0531420707702637',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2477',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,050 of 4,114 Restaurants in Ho Chi Minh City',
            distance: '0.7322296227072661',
            distance_string: '0.7 km',
            bearing: 'south',
            rating: '4.5',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$5 - $15',
            description: 'The Catchy Catering provides delectable food crafted from the heart paired with personal service. Our emphasis is onthe quality of our food, using fresh. We take pride in the fact that our food is prepared from scratch, is authentic, and flavorful. Let us be your personal chef for your Special Event! Buffets set-up, Breakfast, Lunch, Dinner',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d10205168-Reviews-The_Catchy-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d10205168-The_Catchy-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 90 314 57 97',
            website: 'http://www.the-catchy-catering-service.com/',
            email: 'Catchydelivery@gmail.com',
            address_obj: [Object],
            address: '103\\13 Pham van Hai Street, Tan Binh District, Ho Chi Minh City 70000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            booking: [Object],
            reserve_info: [Object],
            establishment_types: [Array]
          }
    ]
}

