export default {
        data: [
          {
            location_id: '10331329',
            name: 'Larva Spicy Noodle',
            latitude: '10.79875',
            longitude: '106.66504',
            num_reviews: '2',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.031029224395752',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3028',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,488 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.3682638716230019',
            distance_string: '0.4 km',
            bearing: 'south',
            rating: '4.0',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d10331329-Reviews-Larva_Spicy_Noodle-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d10331329-Larva_Spicy_Noodle-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 6296 7886',
            website: 'http://www.facebook.com/larvahouseone',
            address_obj: [Object],
            address: '10 Pham Van Hai Ward 2, Tan Binh District, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '12377622',
            name: 'Greed Field Coffee',
            latitude: '10.79875',
            longitude: '106.66504',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '0.3682638716230019',
            distance_string: '0.4 km',
            bearing: 'south',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d12377622-Reviews-Greed_Field_Coffee-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d12377622-Greed_Field_Coffee-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 3844 0275',
            website: 'https://www.facebook.com/CAFE-%C4%90%E1%BB%92NG-XANH-364586483699299/',
            address_obj: [Object],
            address: '10 Pham Van Hai Ward 1, Tan Binh District, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '15612256',
            name: 'Pho Nam Huong',
            latitude: '10.798538',
            longitude: '106.66556',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '2.332820415496826',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '4012',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#3,336 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.4038069449325191',
            distance_string: '0.4 km',
            bearing: 'south',
            is_closed: false,
            is_long_closed: false,
            price_level: '$',
            price: '$50 - $100',
            description: 'We have over 40 years experience, all natural ingredients with heirloom formulas',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d15612256-Reviews-Pho_Nam_Huong-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d15612256-Pho_Nam_Huong-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 90 871 45 69',
            address_obj: [Object],
            address: '328A Nguyen Trong Tuyen Ward 1, Tan Binh, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '12700541',
            name: 'Cay De Vegetarian Restaurant',
            latitude: '10.798477',
            longitude: '106.66283',
            num_reviews: '7',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.1848666667938232',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1304',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,088 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.43507290605636756',
            distance_string: '0.4 km',
            bearing: 'southwest',
            rating: '4.5',
            is_closed: false,
            open_now_text: 'Open Now',
            is_long_closed: false,
            price_level: '$',
            price: '$32,000 - $140,000',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d12700541-Reviews-Cay_De_Vegetarian_Restaurant-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d12700541-Cay_De_Vegetarian_Restaurant-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 6292 8400',
            website: 'https://www.facebook.com/hutieuchaycaybode/',
            email: 'hutieuchaycaybode@yahoo.com',
            address_obj: [Object],
            address: '386 Le Van Sy Ward 2, Tan Binh District, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '19175121',
            name: 'Bun Bo Hue O Cuc',
            latitude: '10.80359',
            longitude: '106.66078',
            num_reviews: '1',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.042945384979248',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2705',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,234 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.44378423514517584',
            distance_string: '0.4 km',
            bearing: 'northwest',
            rating: '5.0',
            is_closed: false,
            open_now_text: 'Open Now',
            is_long_closed: false,
            price_level: '$',
            price: '$2 - $4',
            description: 'The restaurant specializes in Hue dishes, so here serves many delicious dishes of the ancient capital such as duck cake, shrimp cakes with wet meat, delicious cakes ... However, Ngu Binh beef noodle soup is still considered to be outstanding and selected by many people. enjoy because you think this place is so old Hue ... conservative!',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d19175121-Reviews-Bun_Bo_Hue_O_Cuc-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d19175121-Bun_Bo_Hue_O_Cuc-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 90 647 47 07',
            website: 'https://bunbohueocuc.business.site/',
            email: 'nhong299@gmail.com',
            address_obj: [Object],
            address: '69 Thang Long Ward 4, Tan Binh, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '14140845',
            name: "Paulie's Pizza & Pasta",
            latitude: '10.797569',
            longitude: '106.664055',
            num_reviews: '3',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.0386862754821777',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2863',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,355 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.49766210939801775',
            distance_string: '0.5 km',
            bearing: 'south',
            rating: '3.5',
            is_closed: false,
            open_now_text: 'Closed Now',
            is_long_closed: false,
            price_level: '$',
            price: '$69,000 - $329,000',
            description: 'Our names are Paul & Leslie We set up our kitchen by the Heart of Eating & Cooking We season our food with Love We care about our customers as if they are our own family We serve the best Fresh & Delicious Pizza - Pasta & Wraps for only delivery...',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d14140845-Reviews-Paulie_s_Pizza_Pasta-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d14140845-Paulie_s_Pizza_Pasta-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 93 988 14 43',
            website: 'https://www.facebook.com/PauliesPizzaAndPasta/',
            address_obj: [Object],
            address: 'Le Van Sy Ward 2, Tân Bình District, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            booking: [Object],
            reserve_info: [Object],
            establishment_types: [Array]
          },
          {
            location_id: '293925',
            ad_position: 'inline2',
            ad_size: '8X8',
            doubleclick_zone: '',
            detail: '0',
            page_type: 'restaurants',
            mob_ptype: 'app_restaurants'
          },
          {
            location_id: '15035791',
            name: 'MHC Cafe & Restaurant',
            latitude: '10.806197',
            longitude: '106.66622',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '0.5012238974242732',
            distance_string: '0.5 km',
            bearing: 'north',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$68,000 - $1,000,000',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d15035791-Reviews-MHC_Cafe_Restaurant-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d15035791-MHC_Cafe_Restaurant-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 3636 9787',
            website: 'https://www.facebook.com/MHC-Cafe-Restaurant-236564536897668/',
            address_obj: [Object],
            address: '5B Pho Quang BH10 Sky Center Building, Ward 2, Tan Binh, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '12095451',
            name: 'Dim Tu Tac',
            latitude: '10.800014',
            longitude: '106.66038',
            num_reviews: '14',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.2668797969818115',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '974',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#826 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.5041227326206323',
            distance_string: '0.5 km',
            bearing: 'southwest',
            rating: '4.5',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d12095451-Reviews-Dim_Tu_Tac-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d12095451-Dim_Tu_Tac-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 3842 1333',
            website: 'http://www.dimtutac.com/index.cshtml',
            email: 'hotel@dimtutac.com',
            address_obj: [Object],
            address: '202 Hoang Van Thu Ward 9, Phu Nhuan District, Ho Chi Minh City Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '15850710',
            name: 'Sushi World Tan Son Nhat',
            latitude: '10.79994',
            longitude: '106.66041',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '0.50482472501874',
            distance_string: '0.5 km',
            bearing: 'southwest',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$250,000 - $500,000',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d15850710-Reviews-Sushi_World_Tan_Son_Nhat-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d15850710-Sushi_World_Tan_Son_Nhat-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+(84)3842 0228',
            website: 'http://sushiworld.com.vn/vn/',
            address_obj: [Object],
            address: '202 Hoang Van Thu Phu Nhuan, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '12878985',
            name: 'Seoul House',
            latitude: '10.797735',
            longitude: '106.662834',
            num_reviews: '4',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.029697895050049',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3052',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,508 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.510770392629473',
            distance_string: '0.5 km',
            bearing: 'south',
            rating: '3.5',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d12878985-Reviews-Seoul_House-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d12878985-Seoul_House-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 3829 4297',
            address_obj: [Object],
            address: '46 - 48 Bui Thi Xuan, Ho Chi Minh City Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '13988783',
            name: 'Yu Shang Lou - Fine Chinese Cuisine',
            latitude: '10.806698',
            longitude: '106.66439',
            num_reviews: '10',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '2.958024501800537',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3704',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#3,071 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.520996136250668',
            distance_string: '0.5 km',
            bearing: 'north',
            rating: '4.5',
            is_closed: false,
            open_now_text: 'Open Now',
            is_long_closed: false,
            price_level: '$$$$',
            price: '$4 - $3,000,000',
            description: 'Experience the art of Chinese cuisine at YU SHANG LOU restaurant, as our expert chefs take you on a journey of discovery based on excellent food, impeccable service, and an elegant atmosphere. Enjoy a new take on familiar flavors, where we blend eastern and western cooking techniques with a modern, sophisticated flair that will give you a fresh taste of traditional Chinese food.',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d13988783-Reviews-Yu_Shang_Lou_Fine_Chinese_Cuisine-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d13988783-Yu_Shang_Lou_Fine_Chinese_Cuisine-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 7308 7272',
            website: 'http://www.yushanglou.com',
            email: 'yushanglou.vn@gmail.com',
            address_obj: [Object],
            address: '975 Tran Hung Dao Ward 5, District 5, Ho Chi Minh City 72720 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '15662775',
            name: 'Hoang Yen Vietnamese Cuisine',
            latitude: '10.79703',
            longitude: '106.66456',
            num_reviews: '2',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.023747205734253',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3184',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,621 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.5551307252741214',
            distance_string: '0.6 km',
            bearing: 'south',
            rating: '3.5',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d15662775-Reviews-Hoang_Yen_Vietnamese_Cuisine-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d15662775-Hoang_Yen_Vietnamese_Cuisine-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 6685 4088',
            website: 'http://Www.hoangyengroup.com',
            address_obj: [Object],
            address: '363-365 Le Van Sy Ward 12, District 3, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '3727824',
            name: 'Qua Ngon Restaurant',
            latitude: '10.79687',
            longitude: '106.66495',
            num_reviews: '22',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.009640693664551',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3498',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,894 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.5749086938503698',
            distance_string: '0.6 km',
            bearing: 'south',
            rating: '4.0',
            is_closed: false,
            open_now_text: 'Open Now',
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$10 - $50',
            description: 'Located on a busy street at 306 – 308 Le Van Sy, Ward 1, Tan Binh District, Ho Chi Minh City, Qua Ngon Restaurant is famous for its beautiful scene, elegant decorations, finest cookery with Vietnamese food menu such as seafood, specialties, plentiful folk dishes. With slogan “Fresh food and best products used to make sure the food maintains a high quality, without recycled cooking oil and food coloring”, considerate and honest service, reasonable prices, food and safety hygiene, it attracts local and international guests, especially foreign tourists visiting Ho Chi Minh City.',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d3727824-Reviews-Qua_Ngon_Restaurant-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d3727824-Qua_Ngon_Restaurant-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 90 679 79 32',
            website: 'http://www.nhahangquangon.com',
            email: 'lienhe@nhahangquangon.com',
            address_obj: [Object],
            address: '308 306, Le Van Sy Street Ward 1, District Tan Binh, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '6663055',
            name: 'An Phuong Nguyen Co., Ltd',
            latitude: '10.796805',
            longitude: '106.66438',
            num_reviews: '1',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.0139386653900146',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3440',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#2,841 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.5803302734414779',
            distance_string: '0.6 km',
            bearing: 'south',
            rating: '4.0',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d6663055-Reviews-An_Phuong_Nguyen_Co_Ltd-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d6663055-An_Phuong_Nguyen_Co_Ltd-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 3949 0051',
            email: 'saigonbonjour.info@gmail.com',
            address_obj: [Object],
            address: '154/30/64 Pham Van Hai St., Ward 3, Tan Binh District, Ho Chi Minh City 0084 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '293925',
            ad_position: 'inline3',
            ad_size: '8X8',
            doubleclick_zone: '',
            detail: '0',
            page_type: 'restaurants',
            mob_ptype: 'app_restaurants'
          },
          {
            location_id: '15354081',
            name: '2 Chi Em - Com Ga Nha Trang',
            latitude: '10.80668',
            longitude: '106.66691',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '0.581163905578436',
            distance_string: '0.6 km',
            bearing: 'northeast',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d15354081-Reviews-2_Chi_Em_Com_Ga_Nha_Trang-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d15354081-2_Chi_Em_Com_Ga_Nha_Trang-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 90 661 95 78',
            website: 'https://www.facebook.com/2chiem.comganhatrang/',
            address_obj: [Object],
            address: '9 Thich Minh Nguyet Ward 2, Tan Binh District, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '12673895',
            name: 'Simple Coffee',
            latitude: '10.80017',
            longitude: '106.6595',
            num_reviews: '2',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.074558973312378',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2197',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,825 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.5853191599692773',
            distance_string: '0.6 km',
            bearing: 'west',
            rating: '5.0',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d12673895-Reviews-Simple_Coffee-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d12673895-Simple_Coffee-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 7300 0082',
            website: 'http://facebook.com/SimpleCoffeeNTB/',
            address_obj: [Object],
            address: '15-17 Nguyen Thai Binh, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '12829128',
            name: 'SingWok Restaurant',
            latitude: '10.800278',
            longitude: '106.659454',
            num_reviews: '4',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '2.459287405014038',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3967',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#3,303 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.5859332959252234',
            distance_string: '0.6 km',
            bearing: 'west',
            rating: '5.0',
            is_closed: false,
            open_now_text: 'Open Now',
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d12829128-Reviews-SingWok_Restaurant-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d12829128-SingWok_Restaurant-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 97 488 82 91',
            website: 'https://www.facebook.com/haisansingwok/',
            address_obj: [Object],
            address: '15 Nguyen Thai Binh at the backdoor of Maximax Supermarket, Ho Chi Minh City Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '19070728',
            name: 'Craft Beer Bigalow',
            latitude: '10.80725',
            longitude: '106.6654',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '0.5902631141538387',
            distance_string: '0.6 km',
            bearing: 'north',
            is_closed: false,
            open_now_text: 'Open Now',
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d19070728-Reviews-Craft_Beer_Bigalow-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d19070728-Craft_Beer_Bigalow-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 6685 7088',
            website: 'https://www.facebook.com/Craft-Beer-Bigalow-103549247681294/',
            address_obj: [Object],
            address: '1A, Tan Vien Ward 2, Tan Binh, Ho Chi Minh City 72108 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '11886718',
            name: 'Crystal Jade',
            latitude: '10.79924',
            longitude: '106.65988',
            num_reviews: '5',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '2.8133182525634766',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3826',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#3,180 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.5932247573522678',
            distance_string: '0.6 km',
            bearing: 'southwest',
            rating: '3.5',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d11886718-Reviews-Crystal_Jade-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d11886718-Crystal_Jade-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 3811 0359',
            website: 'https://www.facebook.com/CrystalJadeVn/',
            address_obj: [Object],
            address: '415 Hoang Van Thu St 1st Floor, Gala Centre, Ward 2, Tan Binh Dist, Ho Chi Minh City Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '19334762',
            name: 'Steersman Brewery',
            latitude: '10.80262',
            longitude: '106.65898',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '0.608396322039642',
            distance_string: '0.6 km',
            bearing: 'west',
            is_closed: false,
            is_long_closed: false,
            price_level: '$',
            price: '$40,000 - $60,000',
            description: 'In order to let our customer have the most fresh and delicious craft beer, we provide all local craft beer on tap. By selling these beer with a really good price, we try to promote and let more people here understand what is craft beer and how to enjoy it. Let’s explore our chill, cozy place and grab a glass of cold beer, cheers!',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d19334762-Reviews-Steersman_Brewery-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d19334762-Steersman_Brewery-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 93 181 77 04',
            website: 'http://www.steersmanbrewery.vn/',
            email: 'Wayne.su@steersman-brewery.com',
            address_obj: [Object],
            address: '21/1 Giai Phong Ward 4, Tan Binh, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '12829113',
            name: 'Satay House Restaurant',
            latitude: '10.799147',
            longitude: '106.66931',
            num_reviews: '4',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.088460922241211',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2017',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,673 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.6143067215339345',
            distance_string: '0.6 km',
            bearing: 'southeast',
            rating: '4.5',
            is_closed: false,
            open_now_text: 'Open Now',
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d12829113-Reviews-Satay_House_Restaurant-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d12829113-Satay_House_Restaurant-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 3845 8484',
            address_obj: [Object],
            address: '307 Nguyen Van Troi, Ho Chi Minh City Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '16783355',
            name: 'Manwah Hoang Van Thu',
            latitude: '10.79908',
            longitude: '106.6597',
            num_reviews: '7',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.14294171333313',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1556',
            ranking_denominator: '4083',
            ranking_category: 'restaurant',
            ranking: '#1,301 of 4,115 Restaurants in Ho Chi Minh City',
            distance: '0.6196208442822027',
            distance_string: '0.6 km',
            bearing: 'southwest',
            rating: '4.5',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$290,000 - $329,000',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d16783355-Reviews-Manwah_Hoang_Van_Thu-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d16783355-Manwah_Hoang_Van_Thu-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 3811 0463',
            website: 'http://manwah.com.vn/',
            email: 'support.hn@ggg.com.vn',
            address_obj: [Object],
            address: '417 Hoang Van Thu Ward 2, Tan Binh, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          }
        ],
        open_hours_options: {
          closed_count: '17',
          is_set: false,
          low_coverage_primary_message: "Open hours aren't available for all places.",
          timezone: 'Asia/Ho_Chi_Minh',
          unsure_count: '118',
          open_count: '60',
          low_coverage_secondary_message: 'Show all restaurants',
          current_value: 'now'
        },
        paging: { results: '30', total_results: '195' }
}

