const restaurants = {
        data: [
          {
            location_id: '14888080',
            name: 'PizzAmore',
            latitude: '10.823099',
            longitude: '106.62966',
            num_reviews: '14',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.351694345474243',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '757',
            ranking_denominator: '4081',
            ranking_category: 'restaurant',
            ranking: '#649 of 4,112 Restaurants in Ho Chi Minh City',
            distance: '0.0',
            distance_string: '0 m',
            bearing: 'north',
            rating: '5.0',
            is_closed: false,
            open_now_text: 'Closed Now',
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$70,000 - $350,000',
            description: 'PizzAmore is an Open Kitchen Restaurant in Saigon which has as its final mission to offer to our customers the chance to taste the real Italian pizza experience.',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d14888080-Reviews-PizzAmore-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d14888080-PizzAmore-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 166 626 3671',
            website: 'https://www.facebook.com/pizzamore36/',
            email: 'pizzamore36@gmail.com',
            address_obj: [Object],
            address: '36 Road No. 46 Thao Dien Ward, District 2, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            booking: [Object],
            reserve_info: [Object],
            establishment_types: [Array]
          },
          {
            location_id: '14134975',
            name: 'Hu Tieu Mi Hoanh Thanh Goc Sadek',
            latitude: '10.823099',
            longitude: '106.62966',
            num_reviews: '9',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.1975631713867188',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1241',
            ranking_denominator: '4081',
            ranking_category: 'restaurant',
            ranking: '#1,037 of 4,112 Restaurants in Ho Chi Minh City',
            distance: '0.0',
            distance_string: '0 m',
            bearing: 'north',
            rating: '4.5',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d14134975-Reviews-Hu_Tieu_Mi_Hoanh_Thanh_Goc_Sadek-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d14134975-Hu_Tieu_Mi_Hoanh_Thanh_Goc_Sadek-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 98 182 39 86',
            website: 'https://www.facebook.com/gocsadek.66/',
            email: 'gocsadek@gmail.com',
            address_obj: [Object],
            address: '66 D3, Ward 25, Binh Thanh, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '13957863',
            name: 'Pho Kim Hung 3',
            latitude: '10.823099',
            longitude: '106.62966',
            num_reviews: '16',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.2503347396850586',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1022',
            ranking_denominator: '4081',
            ranking_category: 'restaurant',
            ranking: '#864 of 4,112 Restaurants in Ho Chi Minh City',
            distance: '0.0',
            distance_string: '0 m',
            bearing: 'north',
            rating: '4.5',
            is_closed: false,
            open_now_text: 'Closed today',
            is_long_closed: false,
            price_level: '$',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d13957863-Reviews-Pho_Kim_Hung_3-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d13957863-Pho_Kim_Hung_3-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            website: 'http://tranduongco.com',
            address_obj: [Object],
            address: 'Tan Phong Ward, District 7, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '13138018',
            name: 'King Hip Hop',
            latitude: '10.821809',
            longitude: '106.63074',
            num_reviews: '2',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.0184431076049805',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '3349',
            ranking_denominator: '4081',
            ranking_category: 'restaurant',
            ranking: '#2,764 of 4,112 Restaurants in Ho Chi Minh City',
            distance: '0.18561119065473647',
            distance_string: '0.2 km',
            bearing: 'southeast',
            rating: '3.5',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$15,000 - $1,200,000',
            description: 'very comportable cozy place to have a lunch or dinner with the cool beer,beverage and wine. have a nice music, delicious and clean food with your family, freinds,loved one. freindly owner and staffs will welcome you like family. English,Vietnamese,Korean OK',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d13138018-Reviews-King_Hip_Hop-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d13138018-King_Hip_Hop-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 125 294 6096',
            website: 'http://www.facebook.com/kingnhahang',
            address_obj: [Object],
            address: '910B Truong Chinh Ward 15, Tan Binh Dist., Ho Chi Minh City Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '13988697',
            name: 'Ramen Ginza Umemoto',
            latitude: '10.820385',
            longitude: '106.63178',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '0.3807948268201813',
            distance_string: '0.4 km',
            bearing: 'southeast',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d13988697-Reviews-Ramen_Ginza_Umemoto-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d13988697-Ramen_Ginza_Umemoto-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 164 379 4442',
            website: 'https://www.facebook.com/RAMEN-Ginza-Umemoto-2305586932998807/',
            address_obj: [Object],
            address: '8A/A1 Thai Van Lung Ben Nghe ward, District 1, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '17713495',
            name: 'Mo Lau De - Ca Phe',
            latitude: '10.81908',
            longitude: '106.62853',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '0.4639904072334191',
            distance_string: '0.5 km',
            bearing: 'south',
            is_closed: false,
            open_now_text: 'Closed Now',
            is_long_closed: false,
            price_level: '$$ - $$$',
            price: '$2 - $600,000',
            description: 'The graden restaurant in Tan Phu Ward that serves many delious Vietnamese foods and drinks. This is the best place for family and friends.', 
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d17713495-Reviews-Mo_Lau_De_Ca_Phe-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d17713495-Mo_Lau_De_Ca_Phe-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 98 461 78 01',
            website: 'http://mo-lau-de-ca-phe.business.site/',
            email: 'mocafe.restaurant@gmail.com',
            address_obj: [Object],
            address: '23/40 Nguyen Huu Tien Tay Thanh, Tan Phu, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '15849955',
            name: 'Ganh Dau - Galaxy Nguyen Van Qua',
            latitude: '10.83012',
            longitude: '106.62712',
            num_reviews: '6',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.156532049179077',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1462',
            ranking_denominator: '4081',
            ranking_category: 'restaurant',
            ranking: '#1,229 of 4,112 Restaurants in Ho Chi Minh City',
            distance: '0.8292832643415102',
            distance_string: '0.8 km',
            bearing: 'north',
            rating: '5.0',
            is_closed: false,
            open_now_text: 'Closed Now',
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d15849955-Reviews-Ganh_Dau_Galaxy_Nguyen_Van_Qua-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d15849955-Ganh_Dau_Galaxy_Nguyen_Van_Qua-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 28 6683 3331',
            website: 'http://ganhdau.com',
            email: 'wecare.ganhdau@gmail.com',
            address_obj: [Object],
            address: '119B Nguyen Van Qua Dong Hung Thuan, District 12, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '15582729',
            name: 'Lang Chai Phu Quoc',
            latitude: '10.82763',
            longitude: '106.62265',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '0.9174582428417003',
            distance_string: '0.9 km',
            bearing: 'northwest',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d15582729-Reviews-Lang_Chai_Phu_Quoc-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d15582729-Lang_Chai_Phu_Quoc-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 90 834 88 31',
            website: 'http://www.langchaiphuquoc.vn',
            address_obj: [Object],
            address: '35 Phan Van Hon P. Tan Thoi Nhat, Quan 12, Ho Chi Minh City Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '4883267',
            name: 'Com Tam Ba Son',
            latitude: '10.81362',
            longitude: '106.62535',
            num_reviews: '14',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.111252784729004',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '1805',
            ranking_denominator: '4081',
            ranking_category: 'restaurant',
            ranking: '#1,508 of 4,112 Restaurants in Ho Chi Minh City',
            distance: '1.1554767146812275',
            distance_string: '1.2 km',
            bearing: 'southwest',
            rating: '4.0',
            is_closed: false,
            open_now_text: 'Closed Now',
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d4883267-Reviews-Com_Tam_Ba_Son-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d4883267-Com_Tam_Ba_Son-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 8 5413 3122',
            address_obj: [Object],
            address: 'SB10, 1Nguyen Luong Bang Nam Khang, Phu My Hung, Ho Chi Minh City 70000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            booking: [Object],
            reserve_info: [Object],
            establishment_types: [Array]
          },
          {
            location_id: '12219518',
            name: 'First Grill Rib Restaurant',
            latitude: '10.83408',
            longitude: '106.62719',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '1.2516039737600169',
            distance_string: '1.3 km',
            bearing: 'north',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d12219518-Reviews-First_Grill_Rib_Restaurant-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d12219518-First_Grill_Rib_Restaurant-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            address_obj: [Object],
            address: 's11-1 Hung vuong Street, Tan Phong Ward, Ho Chi Minh City Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '4480609',
            name: 'Thu Hao',
            latitude: '10.80828',
            longitude: '106.62632',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '1.6892690871362726',
            distance_string: '1.7 km',
            bearing: 'south',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d4480609-Reviews-Thu_Hao-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d4480609-Thu_Hao-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            address_obj: [Object],
            address: '11 Hung Phuoc 1, Ho Chi Minh City 70000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '15708807',
            name: 'The Iron Ship',
            latitude: '10.83044',
            longitude: '106.64339',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '1.7083639602391443',
            distance_string: '1.7 km',
            bearing: 'northeast',
            is_closed: false,
            open_now_text: 'Closed Now',
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d15708807-Reviews-The_Iron_Ship-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d15708807-The_Iron_Ship-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 94 813 14 18',
            website: 'https://www.facebook.com/TheIronShip/',
            email: 'tuananh230285@yahoo.com',
            address_obj: [Object],
            address: '144 Truong Sa Ward 15, Binh Thanh District, Ho Chi Minh City 700000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '10834165',
            name: 'SumoBBQ - Japanese Grill & Hotpot Restaurant',
            latitude: '10.83562',
            longitude: '106.61954',
            num_reviews: '0',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            distance: '1.7795080887661026',
            distance_string: '1.8 km',
            bearing: 'northwest',
            is_closed: false,
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d10834165-Reviews-SumoBBQ_Japanese_Grill_Hotpot_Restaurant-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d10834165-SumoBBQ_Japanese_Grill_Hotpot_Restaurant-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 4 3722 6354',
            website: 'http://sumobbq.com.vn/',
            address_obj: [Object],
            address: '315 Truong Chinh 6th Floor, Toyota Building, Ho Chi Minh City 700000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '6355843',
            name: 'Goc Cafe - Arts and more',
            latitude: '10.80653',
            longitude: '106.63203',
            num_reviews: '5',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.072968006134033',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2222',
            ranking_denominator: '4081',
            ranking_category: 'restaurant',
            ranking: '#1,848 of 4,112 Restaurants in Ho Chi Minh City',
            distance: '1.8620999867351469',
            distance_string: '1.9 km',
            bearing: 'south',
            rating: '4.0',
            is_closed: false,
            open_now_text: 'Closed Now',
            is_long_closed: false,
            price_level: '',
            description: '',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d6355843-Reviews-Goc_Cafe_Arts_and_more-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d6355843-Goc_Cafe_Arts_and_more-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 93 972 55 99',
            email: 'mail@saigon-stadtfuehrung.de',
            address_obj: [Object],
            address: '6/1A Tran Phu, Phuong 4, Quan 5, Ho Chi Minh City 70000 Vietnam',
            hours: [Object],
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          },
          {
            location_id: '7070094',
            name: 'Kichi Kichi',
            latitude: '10.80654',
            longitude: '106.63447',
            num_reviews: '5',
            timezone: 'Asia/Ho_Chi_Minh',
            location_string: 'Ho Chi Minh City',
            photo: [Object],
            awards: [],
            doubleclick_zone: 'as.vietnam.ho_chi_minh_city',
            preferred_map_engine: 'default',
            raw_ranking: '3.078073501586914',
            ranking_geo: 'Ho Chi Minh City',
            ranking_geo_id: '293925',
            ranking_position: '2126',
            ranking_denominator: '4081',
            ranking_category: 'restaurant',
            ranking: '#1,770 of 4,112 Restaurants in Ho Chi Minh City',
            distance: '1.9164400573658478',
            distance_string: '1.9 km',
            bearing: 'south',
            rating: '4.0',
            is_closed: false,
            is_long_closed: false,
            price_level: '$$ - $$$',
            description: 'Founded in 2009, Kichi Kichi - Express rotary hotpot is undisputed leader of Hotpot Buffet in Vietnam with 25 outlets all over Vietnam and 2 outlets in Singapore at this moment. Our delicious and varied foods come to customer in an unique and modern way: on a conveyer, an excellent combination of Japanese Kaiten style and modern architecture.',
            web_url: 'https://www.tripadvisor.com/Restaurant_Review-g293925-d7070094-Reviews-Kichi_Kichi-Ho_Chi_Minh_City.html',
            write_review: 'https://www.tripadvisor.com/UserReview-g293925-d7070094-Kichi_Kichi-Ho_Chi_Minh_City.html',
            ancestors: [Array],
            category: [Object],
            subcategory: [Array],
            parent_display_name: 'Ho Chi Minh City',
            is_jfy_enabled: false,
            nearest_metro_station: [],
            reviews: [Array],
            phone: '+84 38496841',
            website: 'http://kichi.com.vn/',
            email: 'hcm.suppor@ggg.com.vn',
            address_obj: [Object],
            address: 'Pandora City, 1/1 Truong Chinh, Tay Thanh, Dis Tan Phu, Ho Chi Minh City 70000 Vietnam',
            is_candidate_for_contact_info_suppression: false,
            cuisine: [Array],
            dietary_restrictions: [],
            establishment_types: [Array]
          }
    ]
}

export default restaurants