{
    html_attributions: [],
    next_page_token: 'CqQCIAEAAJZjLWsLcXJlFaP_6bXrqxL0JXl6tK0FSCwI5ryx0PqAlG8KS0a3BW6C8KfcCPahIWhaB70DIYaUpQkYwgePaWGcxABS35fnGqVai3QYosyCINJhSn6H50M-TiKi3PLkNIJ6wGrMocb3HQAskGrWTh1-R0BmdVJvy9kowTeSZZVElJ826W1Ztcor-6vf6BI8rJoV9Irt7wc1jkbGrElB2xqLtkCXm7LdFTnTx7f8bs-s6diDch0oW2wOsJ2Lh5gvqr7fFmHHt21nNEOzpkALFz8p7ITUsBnmZpI3-xTNPquPaUaMZ-N9hxuVJ2OtbzQw-o0Xp90FqM-Kq4ODSVf7jasaJDax0G6Jl2pzGTY7mxH3v44IHFvbFmP44pBqT-pU5RIQWY-O1cB1t63xal4DywqBrBoUVY9qZOk44qLSswXDuqS_favogc0',
    results: [
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png',
        id: '04625769fd933612c8619246ef022a7c73dc794a',
        name: 'Ho Chi Minh City',
        photos: [Array],
        place_id: 'ChIJ0T2NLikpdTERKxE8d61aX_E',
        reference: 'ChIJ0T2NLikpdTERKxE8d61aX_E',
        scope: 'GOOGLE',
        types: [Array],
        vicinity: 'Ho Chi Minh City'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
        id: '0733234cd03c53bd55bcb225456c57e309de33ec',
        name: 'Saigon Village',
        photos: [Array],
        place_id: 'ChIJ9z1ErMMudTERg7BuKpLWXak',
        plus_code: [Object],
        rating: 4.4,
        reference: 'ChIJ9z1ErMMudTERg7BuKpLWXak',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 20,
        vicinity: '523 Tô Hiến Thành, Phường 14, Quận 10'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
        id: 'dc3243affed91c1c9062380d5ee0788bd92263ac',
        name: 'Thanh Binh 3 Hotel',
        photos: [Array],
        place_id: 'ChIJ0Y1TN8AudTERsH-KNK1Y7-s',
        plus_code: [Object],
        rating: 3.9,
        reference: 'ChIJ0Y1TN8AudTERsH-KNK1Y7-s',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 124,
        vicinity: '42 Lữ Gia, Phường 15, Quận 11'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
        id: 'f69d30f2d125abc361a324fa3103b208743eecf2',
        name: 'Valentine Hotel',
        photos: [Array],
        place_id: 'ChIJsTNfm-QudTERzbmJis5kaXQ',
        plus_code: [Object],
        rating: 4.1,
        reference: 'ChIJsTNfm-QudTERzbmJis5kaXQ',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 96,
        vicinity: '93/1 Nguyễn Chí Thanh, Phường 9, Quận 5'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
        id: '1ed73dfd4d0f874059d960a2478a58127930a8c5',
        name: 'Truong Dua Hotel',
        photos: [Array],
        place_id: 'ChIJeb6_6ekudTERYHYvPx0vPws',
        plus_code: [Object],
        rating: 3.7,
        reference: 'ChIJeb6_6ekudTERYHYvPx0vPws',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 156,
        vicinity: '41/2, 284 Lý Thường Kiệt, Phường 14, Quận 10'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
        id: '2f3c9b562983131049c3463a4f23c740abdf3357',
        name: 'Rainbow Hotel',
        photos: [Array],
        place_id: 'ChIJ84O08vwudTERcHOwyTeuoXg',
        plus_code: [Object],
        rating: 3.5,
        reference: 'ChIJ84O08vwudTERcHOwyTeuoXg',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 81,
        vicinity: '41-43 Nguyễn Duy Dương, Phường 8, Quận 5'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/doctor-71.png',
        id: '59b51d27a7cc4711255a3dbb1201854ff85a2341',
        name: 'Cho Ray Hospital',
        opening_hours: [Object],
        photos: [Array],
        place_id: 'ChIJ1_fr7_EudTERWAqRuFPOFJA',
        plus_code: [Object],
        rating: 3.9,
        reference: 'ChIJ1_fr7_EudTERWAqRuFPOFJA',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 1766,
        vicinity: '201B Nguyễn Chí Thanh, Phường 12, Quận 5'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
        id: '5bdbf441ef9882846436b7bff417f554b505d10f',
        name: 'Cosey Hostel',
        photos: [Array],
        place_id: 'ChIJxblNgOsudTERXEtw9NCUHvc',
        plus_code: [Object],
        rating: 5,
        reference: 'ChIJxblNgOsudTERXEtw9NCUHvc',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 2,
        vicinity: '184 Lê Đại Hành, Phường 15, Quận 11'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
        id: 'f906b26c8c692fd10074478e95832e5df3d0b261',
        name: 'Motel Cuu Long',
        photos: [Array],
        place_id: 'ChIJ9VbEK-sudTERbd44rCGlVkc',
        plus_code: [Object],
        rating: 3.7,
        reference: 'ChIJ9VbEK-sudTERbd44rCGlVkc',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 24,
        vicinity: '395 - 397 Lê Đại Hành, Phường 11, Quận 11'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/school-71.png',
        id: '82b2fed3f8758f301aa7227414d71594d46c80f8',
        name: 'Trường Tiểu học Phú Thọ',
        photos: [Array],
        place_id: 'ChIJfxtEtZIudTERtVe06kyBst8',
        plus_code: [Object],
        rating: 4,
        reference: 'ChIJfxtEtZIudTERtVe06kyBst8',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 27,
        vicinity: '322 Tôn Thất Hiệp, Phường 12, Quận 11'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/atm-71.png',
        id: 'adafbc141d65ca97c9fe4f20a7e41114dfe4c261',
        name: 'Vietcombank - Atm',
        opening_hours: [Object],
        place_id: 'ChIJkXOnNu4udTERLuUI0jNYjZk',
        plus_code: [Object],
        rating: 5,
        reference: 'ChIJkXOnNu4udTERLuUI0jNYjZk',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 1,
        vicinity: '241 Lý Thường Kiệt, Phường 7, Quận 10'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
        id: 'b9bf118a27a81385e86d2f0a0a5bd857ec455219',
        name: 'Acb - Atm',
        place_id: 'ChIJPRQ82O8udTERaOlKVreWZWc',
        plus_code: [Object],
        reference: 'ChIJPRQ82O8udTERaOlKVreWZWc',
        scope: 'GOOGLE',
        types: [Array],
        vicinity: '490 Nguyễn Chí Thanh, Phường 7, Quận 10'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
        id: 'c7a31178fc9600c9938681ad28c2adc208878e63',
        name: 'Phòng Khám 18 Phạm Hữu Chí',
        opening_hours: [Object],
        photos: [Array],
        place_id: 'ChIJszGF0fMudTERG47tBqfDf6Q',
        plus_code: [Object],
        rating: 3.1,
        reference: 'ChIJszGF0fMudTERG47tBqfDf6Q',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 7,
        vicinity: '18 Phạm Hữu Chí, Phường 12, Quận 5'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
        id: '31265db0bd54e52a938fdfbd9e6bde056b44210e',
        name: 'Cửa Hàng Foocomart',
        place_id: 'ChIJTfOSafIudTERLmp8SdysX1M',
        plus_code: [Object],
        rating: 4,
        reference: 'ChIJTfOSafIudTERLmp8SdysX1M',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 1,
        vicinity: '247 Nguyễn Chí Thanh, 5'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
        id: 'feffcf938d098d96d5deb279445cbbcef8df0fc9',
        name: 'Thanh Khoi Trading Service Co. Ltd',
        place_id: 'ChIJnXfU-e8udTEReTdAY8aWSTA',
        plus_code: [Object],
        reference: 'ChIJnXfU-e8udTEReTdAY8aWSTA',
        scope: 'GOOGLE',
        types: [Array],
        vicinity: '133A Nguyen Chi Thanh Street, Ward 9, District 5, Phường 5, Quận 10'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
        id: '79b511a367003c87a5436f5a2a7169c6b54fb14f',
        name: 'Bamboo Hostel',
        place_id: 'ChIJt7Yl8-QudTERC4TdF1oHlow',
        plus_code: [Object],
        reference: 'ChIJt7Yl8-QudTERC4TdF1oHlow',
        scope: 'GOOGLE',
        types: [Array],
        vicinity: '186 Nguyễn Tri Phương, Phường 4, Quận 10'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
        id: '462c0c83825f57bdf3424245ba1644dbb2cbcc88',
        name: 'OYO 372 Vy HÃ Hotel',
        place_id: 'ChIJ17J0cMIudTERo5OcC53ToKo',
        plus_code: [Object],
        rating: 5,
        reference: 'ChIJ17J0cMIudTERo5OcC53ToKo',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 2,
        vicinity: '666/46 3 ThÃ¡ng 2, Phường 14, Quận 10'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
        id: 'bcfb9713bbaa190dddf67f2e442a2fdee36734fa',
        name: 'Phong cho thue minh thu',
        place_id: 'ChIJfcjyuO4udTER33Qcpeco3-M',
        plus_code: [Object],
        rating: 1,
        reference: 'ChIJfcjyuO4udTER33Qcpeco3-M',
        scope: 'GOOGLE',
        types: [Array],
        user_ratings_total: 1,
        vicinity: '209 Lý Thường Kiệt, Phường 7, Quận 11'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
        id: '45ae5821159b1c0e881de0d38b5c72b64bed4efe',
        name: 'Pandora Classic Twin',
        place_id: 'ChIJO5rb6ugudTER2rvxCDxBsOw',
        plus_code: [Object],
        reference: 'ChIJO5rb6ugudTER2rvxCDxBsOw',
        scope: 'GOOGLE',
        types: [Array],
        vicinity: '234 Đường 3 Tháng 2, Phường 14, Quận 10'
      },
      {
        geometry: [Object],
        icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png',
        id: 'c775eeadf49b9f6319752046164035c04231020d',
        name: 'Phường 14',
        photos: [Array],
        place_id: 'ChIJQXLZCcMudTERMPo31J-3ty0',
        reference: 'ChIJQXLZCcMudTERMPo31J-3ty0',
        scope: 'GOOGLE',
        types: [Array],
        vicinity: 'Phường 14'
      }
    ],
    status: 'OK'
  }